### Get all Pagamentos
GET http://localhost:8082/pagamento-ms/pagamentos
Cache-Control: no-cache

### Get Pagamento by ID
GET http://localhost:8082/pagamento-ms/pagamentos/1
Cache-Control: no-cache

### Create a new Pagamento
POST http://localhost:8082/pagamento-ms/pagamentos
Cache-Control: no-cache
Content-Type: application/json

{
  "valor": 100.0,
  "nome": "John Doe",
  "numero": "1234567890123456",
  "expiracao": "12/24",
  "cvc": "123",
  "formaPagamentoId": 1,
  "pedidoId": 1
}

### Update a Pagamento
PUT http://localhost:8082/pagamento-ms/pagamentos/1
Cache-Control: no-cache
Content-Type: application/json

{
  "valor": 200.0,
  "nome": "John Doe",
  "numero": "1234567890123456",
  "expiracao": "12/24",
  "cvc": "123",
  "formaPagamentoId": 1,
  "pedidoId": 1
}

### Delete a Pagamento
DELETE http://localhost:8082/pagamento-ms/pagamentos/1
Cache-Control: no-cache

### Confirmar Pagamento
PATCH http://localhost:8082/pagamento-ms/pagamentos/1/confirmar
Cache-Control: no-cache
