### Criar Pedido
POST http://localhost:8082/pedidos-ms/pedidos
Cache-Control: no-cache
Content-Type: application/json

{
  "id": null,
  "dataHora": null,
  "status": null,
  "itemPedidos": [
    {
      "id": null,
      "quantidade": 1,
      "descricao": "Caneta"
    },
    {
      "id": null,
      "quantidade": 2,
      "descricao": "Lapis"
    }
  ]
}

### Get all Pedidos
#GET http://localhost:8082/pedidos-ms/pedidos
GET http://localhost:8080/pedidos
Cache-Control: no-cache


### Get By Id
GET http://localhost:8082/pedidos-ms/pedidos/1
Cache-Control: no-cache
