version: '3.9'

services:
  pagamentodb:
    container_name: pagamentodb
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamentodb
    volumes:
      - pagamento_db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  pagamento_db_data:
